package com.geico.mobile.android.ace.geicoappmodel.emittedstate;

import androidx.annotation.IntDef;
import androidx.annotation.StringDef;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * This file holds annotated types that we can use to efficiently provide type safety
 * for int and String values that represent a limited set of state values within the app.
 * When these values are assigned they either will never be changed or other objects
 * within the app will not need to be notified of a change.
 *
 * @author Kal Tadesse
 */
public interface AceConstantState {

    @IntDef(value = {
            ActionBarCustomization.DEFAULT_TO_PARENT,
            ActionBarCustomization.FORM,
            ActionBarCustomization.ICON_WITHOUT_ARROW_OR_TITLE,
            ActionBarCustomization.NO_ACTION_BAR,
            ActionBarCustomization.NO_ACTION_BUTTONS,
            ActionBarCustomization.SKIPPABLE_FORM,
            ActionBarCustomization.STANDARD,
            ActionBarCustomization.TITLED_WITHOUT_ARROW,
    })
    @Retention(RetentionPolicy.SOURCE)
    @Target({ElementType.CONSTRUCTOR, ElementType.FIELD, ElementType.LOCAL_VARIABLE, ElementType.METHOD, ElementType.PARAMETER, ElementType.TYPE_USE})
    @interface ActionBarCustomization {

        int DEFAULT_TO_PARENT = 5;
        int FORM = 3;
        int ICON_WITHOUT_ARROW_OR_TITLE = 2;
        int NO_ACTION_BAR = -1;
        int NO_ACTION_BUTTONS = 6;
        int SKIPPABLE_FORM = 4;
        int STANDARD = 0;
        int TITLED_WITHOUT_ARROW = 1;
    }

    @StringDef(value = {
            DialogTag.CALL_NUMBER,
            DialogTag.CALL_TO_MAKE_CHANGES,
            DialogTag.CHANGE_DEVICE_NOTIFICATION_SETTINGS,
            DialogTag.CLAIMS_UNDER_CONSTRUCTION_ERROR,
            DialogTag.DESTINATION_NOT_FOUND,
            DialogTag.ENROLL_WITH_DEVICE_UNLOCK,
            DialogTag.FUTURE_AUTOMATIC_PAYMENTS_TERMS_AND_CONDITIONS,
            DialogTag.GENERIC_SERVICE_ERROR,
            DialogTag.GOOGLE_API_AVAILABILITY_ERROR,
            DialogTag.GOOGLE_PLAY_FEEDBACK_ALERT,
            DialogTag.KEEP_ME_LOGGED_IN,
            DialogTag.MAKE_PAYMENT,
            DialogTag.NETWORK_UNAVAILABLE,
            DialogTag.PAYMENT_FAILURE,
            DialogTag.POST_DATED_PAYMENT,
            DialogTag.PUSH_ENROLLMENT_FAILURE,
            DialogTag.PUSH_ENROLLMENT_SUCCESS,
            DialogTag.RESTORE_EMAIL_DRAFT,
            DialogTag.ROADSIDE_CALL_GEICO_DIALOG,
            DialogTag.ROADSIDE_GET_HELP_FASTER_DIALOG,
            DialogTag.ROADSIDE_LOGIN_REQUIRED_DIALOG,
            DialogTag.ROADSIDE_NOT_LOGGED_IN_DIALOG,
            DialogTag.ROADSIDE_WE_ARE_SORRY_DIALOG,
            DialogTag.SEND_EMAIL_UNAVAILABLE,
            DialogTag.SESSION_EXPIRED,
            DialogTag.SERVICE_ERROR_WITH_ALERTS,
            DialogTag.TELEMATICS_CONFIRMATION_ERROR,
            DialogTag.TELEMATICS_INVALID_CONFIRMATION,
            DialogTag.TELEMATICS_INVALID_PHONE_NUMBER,
            DialogTag.TELEMATICS_INVITE_DRIVERS_ERROR,
            DialogTag.TELEMATICS_PHONE_NUMBER_ERROR,
            DialogTag.TELEMATICS_REGISTRATION_EXIT,
            DialogTag.UNABLE_TO_DETERMINE_YOUR_LOCATION,
            DialogTag.UPDATE_YOUR_APP_FOR_FEEDBACK,
            DialogTag.WAIT,
            DialogTag.WAIT_STALLER})
    @Retention(RetentionPolicy.SOURCE)
    @Target({ElementType.FIELD, ElementType.PARAMETER, ElementType.TYPE_USE})
    @interface DialogTag {

        String CALL_NUMBER = "CALL_NUMBER_TAG";
        String CALL_TO_MAKE_CHANGES = "CALL_TO_MAKE_CHANGES";
        String CHANGE_DEVICE_NOTIFICATION_SETTINGS = "CHANGE_DEVICE_NOTIFICATION_SETTINGS";
        String CLAIMS_UNDER_CONSTRUCTION_ERROR = "CLAIMS_UNDER_CONSTRUCTION_ERROR";
        String DESTINATION_NOT_FOUND = "DESTINATION_NOT_FOUND_TAG";
        String ENROLL_WITH_DEVICE_UNLOCK = "ENROLL_WITH_DEVICE_UNLOCK_TAG";
        String FUTURE_AUTOMATIC_PAYMENTS_TERMS_AND_CONDITIONS = "FUTURE_AUTOMATIC_PAYMENTS_TERMS_AND_CONDITIONS";
        String GENERIC_SERVICE_ERROR = "GENERIC_SERVICE_ERROR_DIALOG_TAG";
        String GOOGLE_API_AVAILABILITY_ERROR = "GOOGLE_API_AVAILABILITY_ERROR_DIALOG_TAG";
        String GOOGLE_PLAY_FEEDBACK_ALERT = "GOOGLE_PLAY_FEEDBACK_ALERT";
        String KEEP_ME_LOGGED_IN = "KEEP_ME_LOGGED_IN_TAG";
        String MAKE_PAYMENT = "MAKE_PAYMENT_TAG";
        String NETWORK_UNAVAILABLE = "NETWORK_UNAVAILABLE_DIALOG_TAG";
        String PAYMENT_FAILURE = "PAYMENT_FAILURE_TAG";
        String POST_DATED_PAYMENT = "POST_DATED_PAYMENT";
        String PUSH_ENROLLMENT_FAILURE = "PUSH_ENROLLMENT_FAILURE";
        String PUSH_ENROLLMENT_SUCCESS = "PUSH_ENROLLMENT_SUCCESS";
        String RESTORE_EMAIL_DRAFT = "RESTORE_EMAIL_DRAFT_DIALOG_TAG";
        String ROADSIDE_CALL_GEICO_DIALOG = "ROADSIDE_CALL_GEICO_DIALOG";
        String ROADSIDE_GET_HELP_FASTER_DIALOG = "ROADSIDE_GET_HELP_FASTER_DIALOG";
        String ROADSIDE_LOGIN_REQUIRED_DIALOG = "ROADSIDE_LOGIN_REQUIRED_DIALOG";
        String ROADSIDE_NOT_LOGGED_IN_DIALOG = "ROADSIDE_NOT_LOGGED_IN_DIALOG";
        String ROADSIDE_WE_ARE_SORRY_DIALOG = "ROADSIDE_WE_ARE_SORRY_DIALOG";
        String SEND_EMAIL_UNAVAILABLE = "SEND_EMAIL_UNAVAILABLE_DIALOG_TAG";
        String SERVICE_ERROR_WITH_ALERTS = "SERVICE_ERROR_WITH_ALERTS";
        String SESSION_EXPIRED = "SESSION_EXPIRED_DIALOG_TAG";
        String TELEMATICS_CONFIRMATION_ERROR = "TELEMATICS_CONFIRMATION_ERROR";
        String TELEMATICS_INVALID_CONFIRMATION = "TELEMATICS_INVALID_CONFIRMATION";
        String TELEMATICS_INVALID_PHONE_NUMBER = "TELEMATICS_INVALID_PHONE_NUMBER";
        String TELEMATICS_INVITE_DRIVERS_ERROR = "TELEMATICS_INVITE_DRIVER_ERROR";
        String TELEMATICS_PHONE_NUMBER_ERROR = "TELEMATICS_PHONE_NUMBER_ERROR";
        String TELEMATICS_REGISTRATION_EXIT = "TELEMATICS_REGISTRATION_EXIT";
        String UNABLE_TO_DETERMINE_YOUR_LOCATION = "UNABLE_TO_DETERMINE_YOUR_LOCATION_TAG";
        String UPDATE_YOUR_APP_FOR_FEEDBACK = "UPDATE_YOUR_APP_FOR_FEEDBACK_TAG";
        String WAIT = "WAIT_DIALOG_TAG";
        String WAIT_STALLER = "WAIT_STALLER_DIALOG_TAG";
    }

    /**
     * This annotated type definition represents an emitted state change modelling a programmatically-
     * determined navigation instruction to be handled by a Navigation Controller architecture component.
     */
    @StringDef(value = {
            NavigateAction.ACTIVATE_ACCOUNT_CREATE_FRAGMENT,
            NavigateAction.BILLING_PAYMENT_HISTORY_DETAILS_FRAGMENT,
            NavigateAction.BILLING_CANCEL_PAYMENT_THANK_YOU_FRAGMENT,
            NavigateAction.BILLING_PAYMENT_PLANS_FRAGMENT,
            NavigateAction.CLAIMS_DASHBOARD,
            NavigateAction.CLAIMS_LIST,
            NavigateAction.CONTACT_GEICO_BY_PHONE_ATV_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_AUTO_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_BOAT_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_CANCEL_POLICY_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_CANCEL_REQUEST_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_CHANGE_ADDRESS_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_CHECK_BILL_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_CHECK_PAYMENT_HISTORY_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_CHECK_REQUEST_STATUS_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_CONDO_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_CLAIMS_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_HOMEOWNERS_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_MAKE_PAYMENT_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_MANAGE_CLAIM_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_MANAGE_GLASS_CLAIM_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_MOTORCYCLE_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_PAY_BILL_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_POLICY_CHANGES_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_PROOF_OF_INSURANCE_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_PWC_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_RENTERS_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_REPORT_CLAIM_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_REPORT_GLASS_DAMAGE_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_REQUEST_ROADSIDE_ASSISTANCE_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_REQUEST_TOW_ASSISTANCE_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_RENTERS_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_RV_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_UMBRELLA_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_UPDATE_PAYMENT_METHODS_FRAGMENT,
            NavigateAction.CONTACT_GEICO_BY_PHONE_VIEW_PAYMENT_PLAN_FRAGMENT,
            NavigateAction.COVERAGE_FRAGMENT,
            NavigateAction.DISCOUNT_FRAGMENT,
            NavigateAction.DRIVER_DETAIL_FRAGMENT,
            NavigateAction.EDIT_ACCOUNT_INFO_FRAGMENT,
            NavigateAction.EXPLORE_AR_VIEW,
            NavigateAction.EXPLORE_DISCLAIMER_VIEW,
            NavigateAction.EXPLORE_ONBOARDING_VIEW,
            NavigateAction.EXPLORE_PERMISSIONS_VIEW,
            NavigateAction.PROOF_OF_INSURANCE_BINDER_SELECT_DRIVERS_TO_SHARE_FRAGMENT,
            NavigateAction.PROOF_OF_INSURANCE_BINDER_SELECT_VEHICLES_FRAGMENT,
            NavigateAction.PROOF_OF_INSURANCE_BINDER_SELECT_VEHICLES_TO_SHARE_FRAGMENT,
            NavigateAction.PROOF_OF_INSURANCE_BINDER_SHARE_TO_CONFIRMATION_FRAGMENT,
            NavigateAction.PROOF_OF_INSURANCE_BINDER_SHARE_TO_ERROR_FRAGMENT,
            NavigateAction.PROOF_OF_INSURANCE_CONFIRMATION_TO_DASHBOARD_FRAGMENT,
            NavigateAction.PROOF_OF_INSURANCE_DOCUMENT_SHARE_FRAGMENT,
            NavigateAction.PROOF_OF_INSURANCE_DOCUMENT_START_FRAGMENT,
            NavigateAction.PROOF_OF_INSURANCE_DOCUMENT_START_TO_ERROR_FRAGMENT,
            NavigateAction.PROOF_OF_INSURANCE_DOCUMENT_START_TO_TYPE_OF_LETTER_FRAGMENT,
            NavigateAction.PROOF_OF_INSURANCE_ERROR_TO_DASHBOARD_FRAGMENT,
            NavigateAction.PROOF_OF_INSURANCE_LETTER_DATE_OF_REQUEST_TO_SHARE_FRAGMENT,
            NavigateAction.PROOF_OF_INSURANCE_PRINT_ID_CARDS_FRAGMENT,
            NavigateAction.PROOF_OF_INSURANCE_PRINT_ID_CARDS_TO_ERROR_FRAGMENT,
            NavigateAction.PROOF_OF_INSURANCE_SELECT_VEHICLES_TO_LETTER_DATE_OF_REQUEST_FRAGMENT,
            NavigateAction.PROOF_OF_INSURANCE_TYPE_OF_LETTER_TO_SELECT_DRIVERS_FRAGMENT,
            NavigateAction.PROOF_OF_INSURANCE_TYPE_OF_LETTER_TO_SELECT_VEHICLES_FRAGMENT,
            NavigateAction.TELEMATICS_AUTHORIZATION,
            NavigateAction.TELEMATICS_BATTERY_OPTIMIZATION,
            NavigateAction.TELEMATICS_CONFIRMATION,
            NavigateAction.TELEMATICS_CONTINUE_TO_STANDALONE_APP,
            NavigateAction.TELEMATICS_DASHBOARD,
            NavigateAction.TELEMATICS_OUTAGE,
            NavigateAction.TELEMATICS_FAMILY_REPORT_CARD,
            NavigateAction.TELEMATICS_INVITE_DRIVERS,
            NavigateAction.TELEMATICS_INVITE_DRIVERS_PHONE_ENTRY,
            NavigateAction.TELEMATICS_OUTAGE,
            NavigateAction.TELEMATICS_PERMISSIONS_LOCATION,
            NavigateAction.TELEMATICS_PERMISSIONS_LOCATION_DENIED,
            NavigateAction.TELEMATICS_PERMISSIONS_PHONE_USAGE,
            NavigateAction.TELEMATICS_PERMISSIONS_PHONE_USAGE_DENIED,
            NavigateAction.TELEMATICS_PERMISSIONS_PHYSICAL_ACTIVITY,
            NavigateAction.TELEMATICS_PERMISSIONS_PHYSICAL_ACTIVITY_DENIED,
            NavigateAction.TELEMATICS_PUSH_ENROLLMENT,
            NavigateAction.TELEMATICS_REGISTRATION_CONFIRMATION,
            NavigateAction.TELEMATICS_SCORE_DETAILS,
            NavigateAction.TELEMATICS_TRIP_DETAILS,
            NavigateAction.TELEMATICS_TRIP_HISTORY,
            NavigateAction.USER_SETTINGS_FRAGMENT,
            NavigateAction.VEHICLE_DETAIL_FRAGMENT,
            NavigateAction.WEATHER_ALERT_DETAILS_SERVICE_ERROR_FRAGMENT
    })
    @Target({ElementType.FIELD, ElementType.PARAMETER, ElementType.TYPE_USE})
    @Retention(RetentionPolicy.SOURCE)
    @interface NavigateAction {

        String ACTIVATE_ACCOUNT_CREATE_FRAGMENT = "ACTIVATE_ACCOUNT_CREATE_FRAGMENT";
        String BILLING_CANCEL_PAYMENT_THANK_YOU_FRAGMENT = "BILLING_CANCEL_PAYMENT_THANK_YOU_FRAGMENT";
        String BILLING_PAYMENT_HISTORY_DETAILS_FRAGMENT = "BILLING_PAYMENT_HISTORY_DETAILS_FRAGMENT";
        String BILLING_PAYMENT_PLANS_FRAGMENT = "BILLING_PAYMENT_PLANS_FRAGMENT";
        String CLAIMS_DASHBOARD = "CLAIMS_DASHBOARD_FRAGMENT";
        String CLAIMS_LIST = "CLAIMS_LIST_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_ATV_FRAGMENT = "CONTACT_GEICO_BY_PHONE_ATV_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_AUTO_FRAGMENT = "CONTACT_GEICO_BY_PHONE_AUTO_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_BOAT_FRAGMENT = "CONTACT_GEICO_BY_PHONE_BOAT_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_CANCEL_POLICY_FRAGMENT = "CONTACT_GEICO_BY_PHONE_CANCEL_POLICY_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_CANCEL_REQUEST_FRAGMENT = "CONTACT_GEICO_BY_PHONE_CANCEL_REQUEST_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_CHANGE_ADDRESS_FRAGMENT = "CONTACT_GEICO_BY_PHONE_CHANGE_ADDRESS_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_CHECK_BILL_FRAGMENT = "CONTACT_GEICO_BY_PHONE_CHECK_BILL_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_CHECK_PAYMENT_HISTORY_FRAGMENT = "CONTACT_GEICO_BY_PHONE_CHECK_PAYMENT_HISTORY_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_CHECK_REQUEST_STATUS_FRAGMENT = "CONTACT_GEICO_BY_PHONE_CHECK_REQUEST_STATUS_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_CLAIMS_FRAGMENT = "CONTACT_GEICO_BY_PHONE_CLAIMS_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_CONDO_FRAGMENT = "CONTACT_GEICO_BY_PHONE_CONDO_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_HOMEOWNERS_FRAGMENT = "CONTACT_GEICO_BY_PHONE_HOMEOWNERS_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_MAKE_PAYMENT_FRAGMENT = "CONTACT_GEICO_BY_PHONE_MAKE_PAYMENT_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_MANAGE_CLAIM_FRAGMENT = "CONTACT_GEICO_BY_PHONE_MANAGE_CLAIM_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_MANAGE_GLASS_CLAIM_FRAGMENT = "CONTACT_GEICO_BY_PHONE_MANAGE_GLASS_CLAIM_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_MOTORCYCLE_FRAGMENT = "CONTACT_GEICO_BY_PHONE_MOTORCYCLE_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_PAY_BILL_FRAGMENT = "CONTACT_GEICO_BY_PHONE_PAY_BILL_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_POLICY_CHANGES_FRAGMENT = "CONTACT_GEICO_BY_PHONE_POLICY_CHANGES_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_PROOF_OF_INSURANCE_FRAGMENT = "CONTACT_GEICO_BY_PHONE_PROOF_OF_INSURANCE_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_PWC_FRAGMENT = "CONTACT_GEICO_BY_PHONE_PWC_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_RENTERS_FRAGMENT = "CONTACT_GEICO_BY_PHONE_RENTERS_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_REPORT_CLAIM_FRAGMENT = "CONTACT_GEICO_BY_PHONE_REPORT_CLAIM_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_REPORT_GLASS_DAMAGE_FRAGMENT = "CONTACT_GEICO_BY_PHONE_REPORT_GLASS_DAMAGE_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_REQUEST_ROADSIDE_ASSISTANCE_FRAGMENT = "CONTACT_GEICO_BY_PHONE_REQUEST_ROADSIDE_ASSISTANCE_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_REQUEST_TOW_ASSISTANCE_FRAGMENT = "CONTACT_GEICO_BY_PHONE_REQUEST_TOW_ASSISTANCE_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_RV_FRAGMENT = "CONTACT_GEICO_BY_PHONE_RV_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_UMBRELLA_FRAGMENT = "CONTACT_GEICO_BY_PHONE_UMBRELLA_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_UPDATE_PAYMENT_METHODS_FRAGMENT = "CONTACT_GEICO_BY_PHONE_UPDATE_PAYMENT_METHODS_FRAGMENT";
        String CONTACT_GEICO_BY_PHONE_VIEW_PAYMENT_PLAN_FRAGMENT = "CONTACT_GEICO_BY_PHONE_VIEW_PAYMENT_PLAN_FRAGMENT";
        String COVERAGE_FRAGMENT = "COVERAGE_FRAGMENT";
        String DISCOUNT_FRAGMENT = "DISCOUNT_FRAGMENT";
        String DRIVER_DETAIL_FRAGMENT = "DRIVER_DETAIL_FRAGMENT";
        String EDIT_ACCOUNT_INFO_FRAGMENT = "EDIT_ACCOUNT_INFO_FRAGMENT";
        String EXPLORE_AR_VIEW = "EXPLORE_AR_VIEW";
        String EXPLORE_DISCLAIMER_VIEW = "EXPLORE_DISCLAIMER_VIEW";
        String EXPLORE_ONBOARDING_VIEW = "EXPLORE_ONBOARDING_VIEW";
        String EXPLORE_PERMISSIONS_VIEW = "EXPLORE_PERMISSIONS_VIEW";
        String PROOF_OF_INSURANCE_BINDER_SELECT_DRIVERS_TO_SHARE_FRAGMENT = "PROOF_OF_INSURANCE_BINDER_SELECT_DRIVERS_TO_SHARE_FRAGMENT";
        String PROOF_OF_INSURANCE_BINDER_SELECT_VEHICLES_FRAGMENT = "PROOF_OF_INSURANCE_BINDER_SELECT_VEHICLES_FRAGMENT";
        String PROOF_OF_INSURANCE_BINDER_SELECT_VEHICLES_TO_SHARE_FRAGMENT = "PROOF_OF_INSURANCE_BINDER_SELECT_VEHICLES_TO_SHARE_FRAGMENT";
        String PROOF_OF_INSURANCE_BINDER_SHARE_TO_CONFIRMATION_FRAGMENT = "PROOF_OF_INSURANCE_BINDER_SHARE_TO_CONFIRMATION_FRAGMENT";
        String PROOF_OF_INSURANCE_BINDER_SHARE_TO_ERROR_FRAGMENT = "PROOF_OF_INSURANCE_BINDER_SHARE_TO_ERROR_FRAGMENT";
        String PROOF_OF_INSURANCE_CONFIRMATION_TO_DASHBOARD_FRAGMENT = "ROOF_OF_INSURANCE_CONFIRMATION_TO_DASHBOARD_FRAGMENT";
        String PROOF_OF_INSURANCE_DOCUMENT_SHARE_FRAGMENT = "PROOF_OF_INSURANCE_DOCUMENT_SHARE_FRAGMENT";
        String PROOF_OF_INSURANCE_DOCUMENT_START_FRAGMENT = "PROOF_OF_INSURANCE_DOCUMENT_START_FRAGMENT";
        String PROOF_OF_INSURANCE_DOCUMENT_START_TO_ERROR_FRAGMENT = "PROOF_OF_INSURANCE_DOCUMENT_START_TO_ERROR_FRAGMENT";
        String PROOF_OF_INSURANCE_DOCUMENT_START_TO_TYPE_OF_LETTER_FRAGMENT = "PROOF_OF_INSURANCE_DOCUMENT_START_TO_TYPE_OF_LETTER_FRAGMENT";
        String PROOF_OF_INSURANCE_ERROR_TO_DASHBOARD_FRAGMENT = "PROOF_OF_INSURANCE_ERROR_TO_DASHBOARD_FRAGMENT";
        String PROOF_OF_INSURANCE_LETTER_DATE_OF_REQUEST_TO_SHARE_FRAGMENT = "PROOF_OF_INSURANCE_LETTER_DATE_OF_REQUEST_TO_SHARE_FRAGMENT";
        String PROOF_OF_INSURANCE_PRINT_ID_CARDS_FRAGMENT = "PROOF_OF_INSURANCE_PRINT_ID_CARDS_FRAGMENT";
        String PROOF_OF_INSURANCE_PRINT_ID_CARDS_TO_ERROR_FRAGMENT = "PROOF_OF_INSURANCE_PRINT_ID_CARDS_TO_ERROR_FRAGMENT";
        String PROOF_OF_INSURANCE_SELECT_VEHICLES_TO_LETTER_DATE_OF_REQUEST_FRAGMENT = "PROOF_OF_INSURANCE_SELECT_VEHICLES_TO_LETTER_DATE_OF_REQUEST_FRAGMENT";
        String PROOF_OF_INSURANCE_TYPE_OF_LETTER_TO_SELECT_DRIVERS_FRAGMENT = "PROOF_OF_INSURANCE_TYPE_OF_LETTER_TO_SELECT_DRIVERS_FRAGMENT";
        String PROOF_OF_INSURANCE_TYPE_OF_LETTER_TO_SELECT_VEHICLES_FRAGMENT = "PROOF_OF_INSURANCE_TYPE_OF_LETTER_TO_SELECT_VEHICLES_FRAGMENT";
        String TELEMATICS_AUTHORIZATION = "TELEMATICS_AUTHORIZATION";
        String TELEMATICS_BATTERY_OPTIMIZATION = "TELEMATICS_BATTERY_OPTIMIZATION";
        String TELEMATICS_CONFIRMATION = "TELEMATICS_CONFIRMATION";
        String TELEMATICS_CONTINUE_TO_STANDALONE_APP = "TELEMATICS_CONTINUE_TO_STANDALONE_APP";
        String TELEMATICS_DASHBOARD = "TELEMATICS_DASHBOARD";
        String TELEMATICS_FAMILY_REPORT_CARD = "TELEMATICS_DASHBOARD_TO_FAMILY_REPORT_CARD";
        String TELEMATICS_INVITE_DRIVERS = "TELEMATICS_INVITE_DRIVERS";
        String TELEMATICS_INVITE_DRIVERS_PHONE_ENTRY = "TELEMATICS_INVITE_DRIVERS_PHONE_ENTRY";
        String TELEMATICS_OUTAGE = "TELEMATICS_OUTAGE";
        String TELEMATICS_PERMISSIONS_LOCATION = "TELEMATICS_PERMISSIONS_LOCATION";
        String TELEMATICS_PERMISSIONS_LOCATION_DENIED = "TELEMATICS_PERMISSIONS_LOCATION_DENIED";
        String TELEMATICS_PERMISSIONS_PHONE_USAGE = "TELEMATICS_PERMISSIONS_PHONE_USAGE";
        String TELEMATICS_PERMISSIONS_PHONE_USAGE_DENIED = "TELEMATICS_PERMISSIONS_PHONE_USAGE_DENIED";
        String TELEMATICS_PERMISSIONS_PHYSICAL_ACTIVITY = "TELEMATICS_PERMISSIONS_PHYSICAL_ACTIVITY";
        String TELEMATICS_PERMISSIONS_PHYSICAL_ACTIVITY_DENIED = "TELEMATICS_PERMISSIONS_PHYSICAL_ACTIVITY_DENIED";
        String TELEMATICS_PUSH_ENROLLMENT = "TELEMATICS_PUSH_ENROLLMENT";
        String TELEMATICS_REGISTRATION_CONFIRMATION = "TELEMATICS_REGISTRATION_CONFIRMATION";
        String TELEMATICS_SCORE_DETAILS = "TELEMATICS_SCORE_DETAILS";
        String TELEMATICS_TRIP_DETAILS = "TELEMATICS_TRIP_DETAILS";
        String TELEMATICS_TRIP_HISTORY = "TELEMATICS_TRIP_HISTORY";
        String USER_SETTINGS_FRAGMENT = "USER_SETTINGS_FRAGMENT";
        String VEHICLE_DETAIL_FRAGMENT = "VEHICLE_DETAIL_FRAGMENT";
        String WEATHER_ALERT_DETAILS_SERVICE_ERROR_FRAGMENT = "WEATHER_ALERT_DETAILS_SERVICE_ERROR_FRAGMENT";
    }

    @IntDef(value = {PermissionRequestCode.LOCATION})
    @Target(value = {ElementType.PARAMETER, ElementType.TYPE, ElementType.METHOD, ElementType.FIELD})
    @Retention(RetentionPolicy.SOURCE)
    @interface PermissionRequestCode {

        int LOCATION = 0;
    }

    @IntDef(value = {
            StateType.ACTION_BAR_CUSTOMIZATION,
            StateType.AUTO_SCROLL_STATE,
            StateType.DIALOG_VISIBILITY,
            StateType.ERROR,
            StateType.EXECUTE_WITH_ACTIVITY,
            StateType.NAVIGATION,
            StateType.PERMISSION_REQUEST})
    @Target(value = {ElementType.PARAMETER, ElementType.TYPE, ElementType.METHOD, ElementType.FIELD})
    @Retention(RetentionPolicy.SOURCE)
    @interface StateType {

        int ACTION_BAR_CUSTOMIZATION = 0;
        int AUTO_SCROLL_STATE = 6;
        int DIALOG_VISIBILITY = 1;
        int ERROR = 2;
        int EXECUTE_WITH_ACTIVITY = 5;
        int NAVIGATION = 3;
        int PERMISSION_REQUEST = 4;
    }

    @Target({ElementType.METHOD, ElementType.TYPE})
    @Retention(RetentionPolicy.SOURCE)
    @interface TargetForRefactor {

        String value() default "Things to be done for the purpose of refactoring";
    }

    @IntDef(value = {TimePeriod.AFTERNOON, TimePeriod.EARLY_MORNING, TimePeriod.EVENING, TimePeriod.MORNING})
    @Retention(RetentionPolicy.SOURCE)
    @interface TimePeriod {

        int AFTERNOON = 2;
        int EARLY_MORNING = 0;
        int EVENING = 3;
        int MORNING = 1;
    }
}