package com.geico.mobile.android.ace.geicoappmodel.dashboard;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import androidx.annotation.StringDef;

/**
 * Represents annotated dashboard card types for policy selector and dashboard implementation.
 *
 * @author Gopal Palanisamy and Richard Peirson, GEICO
 */
public interface AceDashboard {

	@StringDef(value = {
			DashboardCardType.ATV,
			DashboardCardType.AUTO,
			DashboardCardType.BOAT,
			DashboardCardType.CHANGE_OF_ADDRESS,
			DashboardCardType.CLAIMS_ACTIVE_ROADSIDE,
			DashboardCardType.CLAIMS_ADDITIONAL_ESTIMATE_RECEIVED,
			DashboardCardType.CLAIMS_AWAITING_PHOTOS,
			DashboardCardType.CLAIMS_ESTIMATE_RECEIVED,
			DashboardCardType.CLAIMS_FORMS_AVAILABLE,
			DashboardCardType.CLAIMS_INSPECTION_REMINDER,
			DashboardCardType.CLAIMS_INSPECT_DAMAGE,
			DashboardCardType.CLAIMS_NEED_ADDITIONAL_PHOTOS,
			DashboardCardType.CLAIMS_REPAIRS_COMPLETE,
			DashboardCardType.CLAIMS_REPAIRS_STARTED,
			DashboardCardType.CLAIMS_REPORT_DAMAGE,
			DashboardCardType.CLAIMS_SCHEDULE_INSPECTION,
			DashboardCardType.CONDO,
			DashboardCardType.CROSS_SELL_SECTION_HEADER,
			DashboardCardType.CYCLE,
			DashboardCardType.DISCOVER_OFFERS,
			DashboardCardType.ENROLL_IN_AUTOMATIC_PAYMENT,
			DashboardCardType.ENROLL_IN_AUTOMATIC_PAYMENT_COMPLETED,
			DashboardCardType.ESIGNATURE,
			DashboardCardType.ESIGNATURE_COMPLETED,
			DashboardCardType.FIRE,
			DashboardCardType.GIVE_BACK,
			DashboardCardType.GET_A_QUOTE,
			DashboardCardType.IDENTITY_THEFT,
			DashboardCardType.HOME_OWNERS,
			DashboardCardType.PERSONAL_ARTICLES,
			DashboardCardType.HOME_OWNERS_PROMOTION,
			DashboardCardType.MISSING_DRIVERS_LICENSE,
			DashboardCardType.MISSING_DRIVERS_LICENSE_COMPLETED,
			DashboardCardType.MOBILE_HOME,
			DashboardCardType.PAPERLESS_BILLING,
			DashboardCardType.PAPERLESS_BILLING_COMPLETED,
			DashboardCardType.PAPERLESS_OPTIONS,
			DashboardCardType.PAPERLESS_OPTIONS_COMPLETED,
			DashboardCardType.PAPERLESS_POLICY,
			DashboardCardType.PAPERLESS_POLICY_COMPLETED,
			DashboardCardType.PAYMENT_COMPLETED,
			DashboardCardType.PAYMENT_DUE,
			DashboardCardType.PAYMENT_OVER_DUE,
			DashboardCardType.PAYMENT_PENDING_CANCELLATION,
			DashboardCardType.POLICY_LINKING,
			DashboardCardType.POLICY_SELECTOR_HEADER,
			DashboardCardType.PUSH_ENROLLMENT,
			DashboardCardType.RENEWAL_UPDATE,
			DashboardCardType.RENTERS,
			DashboardCardType.RENTERS_PROMOTION,
			DashboardCardType.SAVED_QUOTES,
			DashboardCardType.TELEMATICS,
			DashboardCardType.TELEMATICS_NEXT_GEN_SIGNUP,
			DashboardCardType.TELEMATICS_REGISTRATION,
			DashboardCardType.TEXT_ALERTS,
			DashboardCardType.UMBRELLA,
			DashboardCardType.UMBRELLA_PROMOTION,
			DashboardCardType.VEHICLE,
			DashboardCardType.VEHICLE_CARE,
			DashboardCardType.VEHICLE_CARE_RECALL,
			DashboardCardType.WHAT_IS_NEXT_SECTION_HEADER,
			DashboardCardType.WATERCRAFT,
			DashboardCardType.WEATHER_ALERTS_FOR_YOU,
	})
	@Target({ElementType.FIELD, ElementType.PARAMETER, ElementType.TYPE_USE})
	@Retention(RetentionPolicy.SOURCE)
	@interface DashboardCardType {

		String ATV = "ATV";
		String AUTO = "AUTO";
		String BOAT = "BOAT";
		String CHANGE_OF_ADDRESS = "CHANGE_OF_ADDRESS";
		String CLAIMS_ACTIVE_ROADSIDE = "CLAIMS_ACTIVE_ROADSIDE";
		String CLAIMS_ADDITIONAL_ESTIMATE_RECEIVED = "CLAIMS_ADDITIONAL_ESTIMATE_RECEIVED";
		String CLAIMS_AWAITING_PHOTOS = "CLAIMS_AWAITING_PHOTOS";
		String CLAIMS_ESTIMATE_RECEIVED = "CLAIMS_ESTIMATE_RECEIVED";
		String CLAIMS_FORMS_AVAILABLE = "CLAIMS_FORMS_AVAILABLE";
		String CLAIMS_INSPECTION_REMINDER = "CLAIMS_INSPECTION_REMINDER";
		String CLAIMS_INSPECT_DAMAGE = "CLAIMS_INSPECT_DAMAGE";
		String CLAIMS_NEED_ADDITIONAL_PHOTOS = "CLAIMS_NEED_ADDITIONAL_PHOTOS";
		String CLAIMS_REPAIRS_COMPLETE = "CLAIMS_REPAIRS_COMPLETE";
		String CLAIMS_REPAIRS_STARTED = "CLAIMS_REPAIRS_STARTED";
		String CLAIMS_REPORT_DAMAGE = "CLAIMS_REPORT_DAMAGE";
		String CLAIMS_SCHEDULE_INSPECTION = "CLAIMS_SCHEDULE_INSPECTION";
		String CONDO = "CONDO";
		String CROSS_SELL_SECTION_HEADER = "CROSS_SELL_SECTION_HEADER";
		String CYCLE = "CYCLE";
		String DISCOVER_OFFERS = "DISCOVER_OFFERS";
		String ENROLL_IN_AUTOMATIC_PAYMENT = "ENROLL_IN_AUTOMATIC_PAYMENT";
		String ENROLL_IN_AUTOMATIC_PAYMENT_COMPLETED = "ENROLL_IN_AUTOMATIC_PAYMENT_COMPLETED";
		String ESIGNATURE = "ESIGNATURE";
		String ESIGNATURE_COMPLETED = "ESIGNATURE_COMPLETED";
		String FIRE = "FIRE";
		String GET_A_QUOTE = "GET_A_QUOTE";
		String GIVE_BACK = "GIVE_BACK";
		String HOME_OWNERS = "HOME_OWNERS";
		String HOME_OWNERS_PROMOTION = "HOME_OWNERS_PROMOTION";
		String IDENTITY_THEFT = "IDENTITY_THEFT";
		String MISSING_DRIVERS_LICENSE = "MISSING_DRIVERS_LICENSE";
		String MISSING_DRIVERS_LICENSE_COMPLETED = "MISSING_DRIVERS_LICENSE_COMPLETED";
		String MOBILE_HOME = "MOBILE_HOME";
		String PAPERLESS_BILLING = "PAPERLESS_BILLING";
		String PAPERLESS_BILLING_COMPLETED = "PAPERLESS_BILLING_COMPLETED";
		String PAPERLESS_OPTIONS = "PAPERLESS_OPTIONS";
		String PAPERLESS_OPTIONS_COMPLETED = "PAPERLESS_OPTIONS_COMPLETED";
		String PAPERLESS_POLICY = "PAPERLESS_POLICY";
		String PAPERLESS_POLICY_COMPLETED = "PAPERLESS_POLICY_COMPLETED";
		String PAYMENT_COMPLETED = "PAYMENT_COMPLETED";
		String PAYMENT_DUE = "PAYMENT_DUE";
		String PAYMENT_OVER_DUE = "PAYMENT_OVER_DUE";
		String PAYMENT_PENDING_CANCELLATION = "PAYMENT_PENDING_CANCELLATION";
		String PERSONAL_ARTICLES = "PERSONAL_ARTICLES";
		String POLICY_LINKING = "POLICY_LINKING";
		String POLICY_SELECTOR_HEADER = "POLICY_SELECTOR_HEADER";
		String PUSH_ENROLLMENT = "PUSH_ENROLLMENT";
		String RENEWAL_UPDATE = "RENEWAL_UPDATE";
		String RENTERS = "RENTERS";
		String RENTERS_PROMOTION = "RENTERS_PROMOTION";
		String SAVED_QUOTES = "SAVED_QUOTES";
		String TELEMATICS = "TELEMATICS";
		String TELEMATICS_NEXT_GEN_SIGNUP = "TELEMATICS_NEXT_GEN_SIGNUP";
		String TELEMATICS_REGISTRATION = "TELEMATICS_REGISTRATION";
		String TEXT_ALERTS = "TEXT_ALERTS";
		String UMBRELLA = "UMBRELLA";
		String UMBRELLA_PROMOTION = "UMBRELLA_PROMOTION";
		String VEHICLE = "VEHICLE";
		String VEHICLE_CARE = "VEHICLE_CARE";
		String VEHICLE_CARE_RECALL = "VEHICLE_CARE_RECALL";
		String WATERCRAFT = "WATERCRAFT";
		String WEATHER_ALERTS_FOR_YOU = "WEATHER_ALERTS_FOR_YOU";
		String WHAT_IS_NEXT_SECTION_HEADER = "WHAT_IS_NEXT_SECTION_HEADER";
	}

	@StringDef(value = {WhatIsNextPreferences.DASHBOARD_SHARED_PREFERENCES_NAME, WhatIsNextPreferences.ENROLL_IN_AUTOMATIC_PAYMENT,
			WhatIsNextPreferences.ENROLL_IN_AUTOMATIC_PAYMENT_COMPLETED, WhatIsNextPreferences.ESIGNATURE, WhatIsNextPreferences.ESIGNATURE_COMPLETED,
			WhatIsNextPreferences.MISSING_DRIVERS_LICENSE, WhatIsNextPreferences.MISSING_DRIVERS_LICENSE_COMPLETED,
			WhatIsNextPreferences.PAPERLESS_BILLING, WhatIsNextPreferences.PAPERLESS_BILLING_COMPLETED, WhatIsNextPreferences.PAPERLESS_OPTIONS,
			WhatIsNextPreferences.PAPERLESS_OPTIONS_COMPLETED, WhatIsNextPreferences.PAPERLESS_POLICY, WhatIsNextPreferences.PAPERLESS_POLICY_COMPLETED,
			WhatIsNextPreferences.PAYMENT, WhatIsNextPreferences.PAYMENT_COMPLETED, WhatIsNextPreferences.VEHICLE_CARE
	})
	@Target({ElementType.FIELD, ElementType.PARAMETER, ElementType.TYPE_USE})
	@Retention(RetentionPolicy.SOURCE)
	@interface WhatIsNextPreferences {

		String DASHBOARD_SHARED_PREFERENCES_NAME = "dashboardSharedPreferences";
		String ENROLL_IN_AUTOMATIC_PAYMENT = "ENROLL_IN_AUTOMATIC_PAYMENT";
		String ENROLL_IN_AUTOMATIC_PAYMENT_COMPLETED = "ENROLL_IN_AUTOMATIC_PAYMENT_COMPLETED";
		String ESIGNATURE = "ESIGNATURE";
		String ESIGNATURE_COMPLETED = "ESIGNATURE_COMPLETED";
		String MISSING_DRIVERS_LICENSE = "MISSING_DRIVERS_LICENSE";
		String MISSING_DRIVERS_LICENSE_COMPLETED = "MISSING_DRIVERS_LICENSE_COMPLETED";
		String PAPERLESS_BILLING = "PAPERLESS_BILLING";
		String PAPERLESS_BILLING_COMPLETED = "PAPERLESS_BILLING_COMPLETED";
		String PAPERLESS_OPTIONS = "PAPERLESS_OPTIONS";
		String PAPERLESS_OPTIONS_COMPLETED = "PAPERLESS_OPTIONS_COMPLETED";
		String PAPERLESS_POLICY = "PAPERLESS_POLICY";
		String PAPERLESS_POLICY_COMPLETED = "PAPERLESS_POLICY_COMPLETED";
		String PAYMENT = "PAYMENT";
		String PAYMENT_COMPLETED = "PAYMENT_COMPLETED";
		String VEHICLE_CARE = "VEHICLE_CARE";
	}
}