package com.geico.mobile.android.ace.mitsupport.webservices;

import com.geico.mobile.android.ace.coreframework.concurrency.AceChannel;
import com.geico.mobile.android.ace.coreframework.webservices.AceServiceDefinition;
import com.geico.mobile.android.ace.mitsupport.channels.AceMitChannels;
import com.geico.mobile.android.ace.mitsupport.mitmodel.*;
import com.geico.mobile.android.ace.mitsupport.mitmodel.telematics.AceTelematicsDriver;
import com.geico.mobile.android.ace.mitsupport.mitmodel.telematics.MitTelematicsEditRelatedDriverRequest;
import com.geico.mobile.android.ace.mitsupport.mitmodel.telematics.MitTelematicsEditRelatedDriverResponse;
import com.geico.mobile.android.ace.mitsupport.mitmodel.telematics.MitTelematicsGetRelatedDriversRequest;
import com.geico.mobile.android.ace.mitsupport.mitmodel.telematics.MitTelematicsGetRelatedDriversResponse;
import com.geico.mobile.android.ace.mitsupport.mitmodel.telematics.MitTelematicsGetTripDetailsRequest;
import com.geico.mobile.android.ace.mitsupport.mitmodel.telematics.MitTelematicsGetTripDetailsResponse;
import com.geico.mobile.android.ace.mitsupport.mitmodel.telematics.MitTelematicsMessagingEnrollmentRequest;
import com.geico.mobile.android.ace.mitsupport.mitmodel.telematics.MitTelematicsMessagingEnrollmentResponse;
import com.geico.mobile.android.ace.mitsupport.mitmodel.telematics.MitTelematicsRequestConfirmationCodeRequest;
import com.geico.mobile.android.ace.mitsupport.mitmodel.telematics.MitTelematicsRequestConfirmationCodeResponse;
import com.geico.mobile.android.ace.mitsupport.mitmodel.telematics.MitTelematicsRetrieveDriverDataRequest;
import com.geico.mobile.android.ace.mitsupport.mitmodel.telematics.MitTelematicsTripCorrectionsRequest;
import com.geico.mobile.android.ace.mitsupport.mitmodel.telematics.MitTelematicsTripCorrectionsResponse;
import com.geico.mobile.android.ace.mitsupport.mitmodel.telematics.MitTelematicsUpdateEnrollmentRequest;
import com.geico.mobile.android.ace.mitsupport.mitmodel.telematics.MitTelematicsUpdateEnrollmentResponse;
import com.geico.mobile.android.ace.mitsupport.mitmodel.telematics.MitTelematicsValidateConfirmationCodeRequest;
import com.geico.mobile.android.ace.mitsupport.mitmodel.telematics.MitTelematicsValidateConfirmationCodeResponse;

import java.util.Collection;

/**
 * Creates a collection of serviceDefinitions used to connect to MIT - the
 * Mobile Integration TIER.
 *
 * @author Asim Qureshi, GEICO
 * @author Venkatesh Maganahalli, GEICO
 * @author Chris Delia, Lucid Frameworks Corporation
 */
public class AceMitServiceDefinitionsFactory extends AceBaseMitServiceDefinitionsFactory {

    private static final AceMitChannels BEAM = AceMitChannels.BEAM;
    private static final AceMitChannels CLAIMS = AceMitChannels.CLAIMS;
    private static final AceMitChannels CLIENT = AceMitChannels.CLIENT;
    private static final AceMitChannels DATA_SCIENCES = AceMitChannels.DATA_SCIENCES;
    private static final AceMitChannels DIVA = AceMitChannels.DIVA;
    private static final AceMitChannels ECAMS = AceMitChannels.ECAMS;
    private static final AceMitChannels EDS = AceMitChannels.EDS;
    private static final AceMitChannels ERS = AceMitChannels.ERS;
    private static final AceMitChannels MOAT = AceMitChannels.MOAT;
    private static final AceMitChannels NETMAIL = AceMitChannels.NETMAIL;
    private static final AceMitChannels PEAK = AceMitChannels.PEAK;
    private static final AceMitChannels PORTFOLIO = AceMitChannels.PORTFOLIO;
    private static final AceMitChannels RIDE = AceMitChannels.RIDE;
    private static final AceMitChannels SALES = AceMitChannels.SALES;
    private static final AceMitChannels TELEMATICS = AceMitChannels.TELEMATICS;
    private static final AceMitChannels TIER_ONLY = AceMitChannels.TIER_ONLY;
    private static final AceMitChannels UMBRELLA = AceMitChannels.UMBRELLA;
    private static final AceMitChannels VEHICLE_CARE = AceMitChannels.VEHICLE_CARE;
    private static final AceMitChannels WEATHER_COMPANY_ALERTS = AceMitChannels.WEATHER_COMPANY_ALERTS;
    private static final AceMitChannels WEATHER_COMPANY_DATA = AceMitChannels.WEATHER_COMPANY_DATA;

    @Override
    protected void appendDefinitions(Collection<AceServiceDefinition<?, ?>> list) {
        appendDefinition(list, MitAccountRecoveryAuthenticateRequest.class, MitAccountRecoveryAuthenticateResponse.class, "accountRecoveryAuthenticate/v1", ECAMS);
        appendDefinition(list, MitAccountRecoverySendEmailRequest.class, MitAccountRecoverySendEmailResponse.class, "accountRecoverySendEmail/v1", ECAMS);
        appendDefinition(list, MitAccountRecoverySendPinRequest.class, MitAccountRecoverySendPinResponse.class, "accountRecoverySendPin/v1", ECAMS);
        appendDefinition(list, MitAccountRecoveryValidatePinRequest.class, MitAccountRecoveryValidatePinResponse.class, "accountRecoveryValidatePin/v1", ECAMS);
        appendDefinition(list, MitActivateUserAccountRequest.class, MitActivateUserAccountResponse.class, "activateUserAccount/v1", ECAMS);
        appendDefinition(list, MitAddCardResourceToWalletForAlternatePayerRequest.class, MitAddResourceToWalletResponse.class, "addCardResourceToWalletForAlternatePayer/v1", BEAM);
        appendDefinition(list, MitAddCardResourceToWalletForNewAlternatePayerRequest.class, MitAddResourceToWalletResponse.class, "addCardResourceToWalletForNewAlternatePayer/v1", BEAM);
        appendDefinition(list, MitAddCardResourceToWalletRequest.class, MitAddResourceToWalletResponse.class, "addCardResourceToWallet/v1", BEAM);
        appendDefinition(list, MitAddCheckResourceToWalletForAlternatePayerRequest.class, MitAddResourceToWalletResponse.class, "addCheckResourceToWalletForAlternatePayer/v1", BEAM);
        appendDefinition(list, MitAddCheckResourceToWalletForNewAlternatePayerRequest.class, MitAddResourceToWalletResponse.class, "addCheckResourceToWalletForNewAlternatePayer/v1");
        appendDefinition(list, MitAddCheckResourceToWalletRequest.class, MitAddResourceToWalletResponse.class, "addCheckResourceToWallet/v1");
        appendDefinition(list, MitAuthenticateThirdPartyClaimantRequest.class, MitAuthenticateThirdPartyClaimantResponse.class, "authenticateThirdPartyClaimant/v1", CLAIMS);
        appendDefinition(list, MitCancelDigitalDispatchErsRequest.class, MitCancelDigitalDispatchErsResponse.class, "cancelDigitalDispatchErs/v1", CLAIMS);
        appendDefinition(list, MitCancelPaymentRequest.class, MitCancelPaymentResponse.class, "cancelPayment/v1");
        appendDefinition(list, MitChangePasswordRequest.class, MitChangePasswordResponse.class, "changePassword/v1", ECAMS);
        appendDefinition(list, MitChangePaymentDueDayRequest.class, MitChangePaymentDueDayResponse.class, "changePaymentDueDay/v1");
        appendDefinition(list, MitChangePayPlanRequest.class, MitChangePayPlanResponse.class, "changePayPlan/v1", BEAM);
        appendDefinition(list, MitCheckInRequest.class, MitCheckInResponse.class, "checkIn/v1", TIER_ONLY);
        appendDefinition(list, MitClaimsNotificationRequest.class, MitClaimsNotificationResponse.class, "claimsNotification/v1", CLAIMS);
        appendDefinition(list, MitClientRegistrationRequest.class, MitClientRegistrationResponse.class, "clientRegistration/v1");
        appendDefinition(list, MitDashboardHeaderContentRequest.class, MitDashboardHeaderContentResponse.class, "dashboardHeaderContent/v1", CLAIMS);
        appendDefinition(list, MitDeleteAlternatePayerRequest.class, MitDeleteAlternatePayerResponse.class, "deleteAlternatePayer/v1", CLIENT);
        appendDefinition(list, MitDigitalDispatchErsWithLoginRequest.class, MitDigitalDispatchErsResponse.class, "digitalDispatchErsWithLogin/v1", CLAIMS);
        appendDefinition(list, MitDigitalDispatchErsWithoutLoginRequest.class, MitDigitalDispatchErsResponse.class, "digitalDispatchErsWithoutLogin/v1", CLAIMS);
        appendDefinition(list, MitDivaIntentRequest.class, MitDivaIntentResponse.class, "divaIntent/v1", DIVA);
        appendDefinition(list, MitDivaStartConversationRequest.class, MitDivaStartConversationResponse.class, "divaStartConversation/v1", DIVA);
        appendDefinition(list, MitDivaUpdateBackgroundRequest.class, MitDivaUpdateBackgroundResponse.class, "divaUpdateBackground/v1", DIVA);
        appendDefinition(list, MitEditAutomaticPaymentRequest.class, MitEditAutomaticPaymentResponse.class, "editAutomaticPayment/v1");
        appendDefinition(list, MitEmailIdCardsPdfRequest.class, MitShareIdCardsPdfResponse.class, "emailIdCardsPdf/v1", EDS);
        appendDefinition(list, MitEnrollInEBillRequest.class, MitEnrollInEBillResponse.class, "enrollInEBill/v1", BEAM);
        appendDefinition(list, MitEnrollInRecurringPaymentsByAlternatePayerWithCardRequest.class, MitEnrollInRecurringPaymentsResponse.class, "enrollInRecurringPaymentsByAlternatePayerWithCard/v1", BEAM);
        appendDefinition(list, MitEnrollInRecurringPaymentsByAlternatePayerWithCheckRequest.class, MitEnrollInRecurringPaymentsResponse.class, "enrollInRecurringPaymentsByAlternatePayerWithCheck/v1");
        appendDefinition(list, MitEnrollInRecurringPaymentsByNewAlternatePayerWithCardRequest.class, MitEnrollInRecurringPaymentsResponse.class, "enrollInRecurringPaymentsByNewAlternatePayerWithCard/v1", BEAM);
        appendDefinition(list, MitEnrollInRecurringPaymentsByNewAlternatePayerWithCheckRequest.class, MitEnrollInRecurringPaymentsResponse.class, "enrollInRecurringPaymentsByNewAlternatePayerWithCheck/v1");
        appendDefinition(list, MitEnrollInRecurringPaymentsWithNewCardResourceRequest.class, MitEnrollInRecurringPaymentsResponse.class, "enrollInRecurringPaymentsWithNewCardResource/v1", BEAM);
        appendDefinition(list, MitEnrollInRecurringPaymentsWithNewCheckResourceRequest.class, MitEnrollInRecurringPaymentsResponse.class, "enrollInRecurringPaymentsWithNewCheckResource/v1", BEAM);
        appendDefinition(list, MitEnrollInRecurringPaymentsWithWalletResourceRequest.class, MitEnrollInRecurringPaymentsResponse.class, "enrollInRecurringPaymentsWithWalletResource/v1", BEAM);
        appendDefinition(list, MitEstablishOasisPolicySessionRequest.class, MitEstablishOasisPolicySessionResponse.class, "establishOasisPolicySession/v1");
        appendDefinition(list, MitEstablishVehiclePolicySessionRequest.class, MitEstablishVehiclePolicySessionResponse.class, "establishVehiclePolicySession/v1");
        appendDefinition(list, MitEventLogRequest.class, MitEventLogResponse.class, "eventLog/v1");
        appendDefinition(list, MitFaxIdCardsPdfRequest.class, MitShareIdCardsPdfResponse.class, "faxIdCardsPdf/v1", EDS);
        appendDefinition(list, MitFederatedLoginRequest.class, MitFederatedLoginResponse.class, "federatedLogin/v1", ECAMS);
        appendDefinition(list, MitGetARideRequest.class, MitGetARideResponse.class, "getARide/v1", RIDE);
        appendDefinition(list, MitIdCardsRequest.class, MitIdCardsResponse.class, "idCards/v1", EDS);
        appendDefinition(list, MitIdCardBackTextRequest.class, MitIdCardBackTextResponse.class, "idCardBackText/v1");
        appendDefinition(list, MitIvrPolicyInquiryRequest.class, MitIvrPolicyInquiryResponse.class, "ivrPolicyInquiry/v1");
        appendDefinition(list, MitKeepInsiteSessionAliveRequest.class, MitKeepInsiteSessionAliveResponse.class, "keepInsiteSessionAlive/v1");
        appendDefinition(list, MitLinkPolicyRequest.class, MitLinkPolicyResponse.class, "linkPolicy/v1", ECAMS);
        appendDefinition(list, MitListClaimsWithAlertNotificationsRequest.class, MitListClaimsResponse.class, "listClaimsWithAlertNotifications/v1", CLAIMS);
        appendDefinition(list, MitListCoveragesRequest.class, MitListCoveragesResponse.class, "listCoverages/v1");
        appendDefinition(list, MitListDiscountsRequest.class, MitListDiscountsResponse.class, "listDiscounts/v1");
        appendDefinition(list, MitListPolicyBillingDocumentsRequest.class, MitDocumentSetsResponse.class, "listPolicyBillingDocuments/v1", EDS);
        appendDefinition(list, MitListPolicyDocumentsRequest.class, MitDocumentSetsResponse.class, "listPolicyDocuments/v1", EDS);
        appendDefinition(list, MitLogConversationRequest.class, MitLogConversationResponse.class, "logConversation/v1");
        appendDefinition(list, MitLogOperationEventsRequest.class, MitLogOperationEventsResponse.class, "logOperationEvents/v1");
        appendDefinition(list, MitLogoutUserSessionRequest.class, MitLogoutUserSessionResponse.class, "logoutUserSession/v1");
        appendDefinition(list, MitLogPortfolioEventsRequest.class, MitLogPortfolioEventsResponse.class, "logPortfolioEvents/v1", ECAMS);
        appendDefinition(list, MitLookupThirdPartyClaimRequest.class, MitLookupThirdPartyClaimResponse.class, "lookupThirdPartyClaim/v1", CLAIMS);
        appendDefinition(list, MitMailIdCardsPdfRequest.class, MitShareIdCardsPdfResponse.class, "mailIdCardsPdf/v1", EDS);
        appendDefinition(list, MitMakePaymentRequest.class, MitMakePaymentResponse.class, "makePayment/v1");
        appendDefinition(list, MitUpdatePaidInFullDiscountStatusRequest.class, MitUpdatePaidInFullDiscountStatusResponse.class, "updatePaidInFullDiscountStatus/v1");
        appendDefinition(list, MitMaxPaymentDateRequest.class, MitMaxPaymentDateResponse.class, "maxPaymentDate/v1");
        appendDefinition(list, MitMessagingEnrollmentRequest.class, MitPushNotificationsEnrollmentResponse.class, "messagingEnrollment/v1");
        appendDefinition(list, MitMoatSalesQuotesRecallRequest.class, MitMoatSalesQuotesRecallResponse.class, "moatSalesQuotesRecall/v1", MOAT);
        appendDefinition(list, MitOAuthInitialLoginRequest.class, MitOAuthLoginResponse.class, "oAuthInitialLogin/v1");
        appendDefinition(list, MitOAuthRefreshLoginRequest.class, MitOAuthLoginResponse.class, "oAuthRefreshLogin/v1");
        appendDefinition(list, MitPaperlessPolicyRequest.class, MitPaperlessPolicyResponse.class, "paperlessPolicy/v1", PEAK);
        appendDefinition(list, MitPayLaterByAlternatePayerWithCardRequest.class, MitPayLaterByCardResponse.class, "payLaterByAlternatePayerWithCard/v1");
        appendDefinition(list, MitPayLaterByAlternatePayerWithCheckRequest.class, MitPayLaterByCheckResponse.class, "payLaterByAlternatePayerWithCheck/v1");
        appendDefinition(list, MitPayLaterByCardRequest.class, MitPayLaterByCardResponse.class, "payLaterByCard/v1");
        appendDefinition(list, MitPayLaterByCheckRequest.class, MitPayLaterByCheckResponse.class, "payLaterByCheck/v1");
        appendDefinition(list, MitPayLaterByNewAlternatePayerWithCardRequest.class, MitPayLaterByCardResponse.class, "payLaterByNewAlternatePayerWithCard/v1");
        appendDefinition(list, MitPayLaterByNewAlternatePayerWithCheckRequest.class, MitPayLaterByCheckResponse.class, "payLaterByNewAlternatePayerWithCheck/v1");
        appendDefinition(list, MitPayLaterWithStoredAccountRequest.class, MitPayNowWithStoredAccountResponse.class, "payLaterWithStoredAccount/v1", BEAM);
        appendDefinition(list, MitPaymentHistoryRequest.class, MitPaymentHistoryResponse.class, "paymentHistory/v1", BEAM);
        appendDefinition(list, MitPaymentScheduleRequest.class, MitPaymentScheduleResponse.class, "paymentSchedule/v1");
        appendDefinition(list, MitPayNowByAlternatePayerWithCardRequest.class, MitPayNowByCardResponse.class, "payNowByAlternatePayerWithCard/v1");
        appendDefinition(list, MitPayNowByAlternatePayerWithCheckRequest.class, MitPayNowByCheckResponse.class, "payNowByAlternatePayerWithCheck/v1");
        appendDefinition(list, MitPayNowByCardRequest.class, MitPayNowByCardResponse.class, "payNowByCard/v1");
        appendDefinition(list, MitPayNowByCheckRequest.class, MitPayNowByCheckResponse.class, "payNowByCheck/v1");
        appendDefinition(list, MitPayNowByNewAlternatePayerWithCardRequest.class, MitPayNowByCardResponse.class, "payNowByNewAlternatePayerWithCard/v1");
        appendDefinition(list, MitPayNowByNewAlternatePayerWithCheckRequest.class, MitPayNowByCheckResponse.class, "payNowByNewAlternatePayerWithCheck/v1", BEAM);
        appendDefinition(list, MitPayNowWithStoredAccountRequest.class, MitPayNowWithStoredAccountResponse.class, "payNowWithStoredAccount/v1", BEAM);
        appendDefinition(list, MitPolicyDocumentRequest.class, MitPolicyDocumentResponse.class, "policyDocument/v1");
        appendDefinition(list, MitPolicyInfoRequest.class, MitPolicyInfoResponse.class, "policyInfo/v1");
        appendDefinition(list, MitPostponeAutomaticPaymentRequest.class, MitUpdateAutomaticPaymentResponse.class, "postponeAutomaticPayment/v1");
        appendDefinition(list, MitPostponeRecurringPaymentRequest.class, MitPostponeRecurringPaymentResponse.class, "postponeRecurringPayment/v1", BEAM);
        appendDefinition(list, MitPrepareForAccountRecoveryRequest.class, MitPrepareForAccountRecoveryResponse.class, "prepareForAccountRecovery/v1", ECAMS);
        appendDefinition(list, MitPrepareForCustomerSatisfactionSurveyRequest.class, MitPrepareForCustomerSatisfactionSurveyResponse.class, "prepareForCustomerSatisfactionSurvey/v1");
        appendDefinition(list, MitPrepareForDashfolioRequest.class, MitPrepareForDashfolioResponse.class, "prepareForDashfolio/v1", PORTFOLIO);
        appendDefinition(list, MitPrepareForConversationRequest.class, MitPrepareForConversationResponse.class, "prepareForConversationIntent/v1", DIVA);
        appendDefinition(list, MitPrepareForIdCardsRequest.class, MitPrepareForIdCardsResponse.class, "prepareForIdCards/v1", PEAK);
        appendDefinition(list, MitPrepareForPaymentRequest.class, MitPrepareForPaymentResponse.class, "prepareForPayment/v1");
        appendDefinition(list, MitPrepareForRecommendationsRequest.class, MitPrepareForRecommendationsResponse.class, "prepareForRecommendations/v1");
        appendDefinition(list, MitPrepareForVehicleCareRequest.class, MitPrepareForVehicleCareResponse.class, "prepareForVehicleCare/v1", VEHICLE_CARE);
        appendDefinition(list, MitPrepareForWeatherAlertsRequest.class, MitPrepareForWeatherAlertsResponse.class, "prepareForWeatherAlerts/v1", WEATHER_COMPANY_ALERTS);
        appendDefinition(list, MitPrepareForWeatherAlertsEnrollmentRequest.class, MitPrepareForWeatherAlertsEnrollmentResponse.class, "prepareForWeatherAlertsEnrollment/v1", TIER_ONLY);
        appendDefinition(list, MitPrepareToActivateUserAccountRequest.class, MitPrepareToActivateUserAccountResponse.class, "prepareToActivateUserAccount/v1", ECAMS);
        appendDefinition(list, MitPrepareToContactUsRequest.class, MitPrepareToContactUsResponse.class, "prepareToContactUs/v1");
        appendDefinition(list, MitPrepareToDigitalDispatchErsRequest.class, MitPrepareToDigitalDispatchErsResponse.class, "prepareToDigitalDispatchErs/v1", ERS);
        appendDefinition(list, MitPrepareToFindGasRequest.class, MitPrepareToFindGasResponse.class, "prepareToFindGas/v1");
        appendDefinition(list, MitPrepareToFindParkingRequest.class, MitPrepareToFindParkingResponse.class, "prepareToFindParking/v1");
        appendDefinition(list, MitPrepareToUpdateAutomaticPaymentRequest.class, MitPrepareToUpdateAutomaticPaymentResponse.class, "prepareToUpdateAutomaticPayment/v1");
        appendDefinition(list, MitPrepareToUpdatePaymentPlanRequest.class, MitPrepareToUpdatePaymentPlanResponse.class, "prepareToUpdatePaymentPlan/v1");
        appendDefinition(list, MitPrepareToUpdateTextAlertsRequest.class, MitPrepareToUpdateTextAlertsResponse.class, "prepareToUpdateTextAlerts/v1", NETMAIL);
        appendDefinition(list, MitPrepareToUpdateUserLoginInformationRequest.class, MitPrepareToUpdateUserLoginInformationResponse.class, "prepareToUpdateUserLoginInformation/v1", ECAMS);
        appendDefinition(list, MitPushNotificationsEnrollmentRequest.class, MitPushNotificationsEnrollmentResponse.class, "pushNotificationsEnrollment/v1");
        appendDefinition(list, MitQuoteRentersInsuranceRequest.class, MitQuoteRentersInsuranceResponse.class, "quoteRentersInsurance/v1", MOAT);
        appendDefinition(list, MitRecoveryLoginRequest.class, MitRecoveryLoginResponse.class, "recoveryLogin/v1");
        appendDefinition(list, MitRefreshOasisPolicySessionRequest.class, MitRefreshOasisPolicySessionResponse.class, "refreshOasisPolicySession/v1");
        appendDefinition(list, MitRemoveResourceFromWalletRequest.class, MitRemoveResourceFromWalletResponse.class, "removeResourceFromWallet/v1", BEAM);
        appendDefinition(list, MitResetPasswordRequest.class, MitResetPasswordResponse.class, "resetPassword/v1", ECAMS);
        appendDefinition(list, MitRetrieveAccountInformationRequest.class, MitRetrieveAccountInformationResponse.class, "retrieveAccountInformation/v1", ECAMS);
        appendDefinition(list, MitRetrieveAccountLevelBillingSummaryRequest.class, MitRetrieveAccountLevelBillingSummaryResponse.class, "retrieveAccountLevelBillingSummary/v1", BEAM);
        appendDefinition(list, MitRetrieveAccountsForLinkingRequest.class, MitRetrieveAccountsForLinkingResponse.class, "retrieveAccountsForLinking/v1", ECAMS);
        appendDefinition(list, MitRetrieveAvailablePayPlansRequest.class, MitRetrieveAvailablePayPlansResponse.class, "retrieveAvailablePayPlans/v1", BEAM);
        appendDefinition(list, MitRetrieveBillingInformationRequest.class, MitRetrieveBillingInformationResponse.class, "retrieveBillingInformation/v1", BEAM);
        appendDefinition(list, MitRetrieveContactCategoryRequest.class, MitRetrieveContactCategoryResponse.class, "retrieveContactCategory/v1");
        appendDefinition(list, MitRetrieveCoverageReportRequest.class, MitRetrieveCoverageReportResponse.class, "retrieveCoverageReport/v1", PEAK);
        appendDefinition(list, MitRetrieveCrossSellProbabilityRequest.class, MitRetrieveCrossSellProbabilityResponse.class, "retrieveCrossSellProbability/v1", DATA_SCIENCES);
        appendDefinition(list, MitRetrieveCurrentDateTimeRequest.class, MitRetrieveCurrentDateTimeResponse.class, "retrieveCurrentDateTime/v1");
        appendDefinition(list, MitRetrieveCycleLoginDetailsRequest.class, MitRetrieveCycleLoginDetailsResponse.class, "retrieveCycleLoginDetails/v1", ECAMS);
        appendDefinition(list, MitRetrieveDigitalErsDispatchDetailsRequest.class, MitRetrieveDigitalErsDispatchDetailsResponse.class, "retrieveDigitalErsDispatchDetails/v1", CLAIMS);
        appendDefinition(list, MitRetrieveDiscountReportRequest.class, MitRetrieveDiscountReportResponse.class, "retrieveDiscountReport/v1", PEAK);
        appendDefinition(list, MitRetrieveIdCardConciseRequest.class, MitRetrieveIdCardsResponse.class, "retrieveIdCardConcise/v1", EDS);
        appendDefinition(list, MitRetrieveIdCardsPdfRequest.class, MitRetrieveIdCardsPdfResponse.class, "retrieveIdCardsPdf/v1", EDS);
        appendDefinition(list, MitRetrieveIdCardsRequest.class, MitRetrieveIdCardsResponse.class, "retrieveIdCards/v1", EDS);
        appendDefinition(list, MitRetrieveIsisCoverageReportRequest.class, MitRetrieveIsisCoverageReportResponse.class, "retrieveIsisCoverageReport/v1");
        appendDefinition(list, MitRetrieveIsisDiscountReportRequest.class, MitRetrieveIsisDiscountReportResponse.class, "retrieveIsisDiscountReport/v1");
        appendDefinition(list, MitRetrieveMoatCarrierBillingInformationRequest.class, MitRetrieveMoatCarrierBillingInformationResponse.class, "retrieveMoatCarrierBillingInformation/v1");
        appendDefinition(list, MitRetrieveMsiPolicyInformationRequest.class, MitRetrieveMsiPolicyInformationResponse.class, "retrieveMsiPolicyInformation/v1", BEAM);
        appendDefinition(list, MitRetrieveReadOnlyPolicyRequest.class, MitRetrieveReadOnlyPolicyResponse.class, "retrieveReadOnlyPolicy/v1", ECAMS);
        appendDefinition(list, MitRetrieveSecondaryInsuredPhoneNumbersRequest.class, MitRetrieveSecondaryInsuredPhoneNumbersResponse.class, "retrieveSecondaryInsuredPhoneNumbers/v1", ECAMS);
        appendDefinition(list, MitRetrieveServiceDefinitionsRequest.class, MitRetrieveServiceDefinitionsResponse.class, "retrieveServiceDefinitions/v1");
        appendDefinition(list, MitRetrieveUmbrellaTeaserQuoteRequest.class, MitRetrieveUmbrellaTeaserQuoteResponse.class, "retrieveUmbrellaTeaserQuote/v1", UMBRELLA);
        appendDefinition(list, MitRetrieveWeatherAlertDetailsRequest.class, MitRetrieveWeatherAlertDetailsResponse.class, "retrieveWeatherAlertDetails/v1", WEATHER_COMPANY_DATA);
        appendDefinition(list, MitRetrieveWeatherAlertsRequest.class, MitRetrieveWeatherAlertsResponse.class, "retrieveWeatherAlerts/v1", WEATHER_COMPANY_DATA);
        appendDefinition(list, MitReverseLinkPolicyRequest.class, MitReverseLinkPolicyResponse.class, "reverseLinkPolicy/v1", ECAMS);
        appendDefinition(list, MitSubmitContactUsCommentsQuestionsRequest.class, MitSubmitContactUsCommentsQuestionsResponse.class, "submitContactUsCommentsQuestions/v1");
        appendDefinition(list, MitSubmitUserCommentsRequest.class, MitSubmitUserCommentsResponse.class, "submitUserComments/v1", ECAMS);
        appendDefinition(list, MitTelematicsEditRelatedDriverRequest.class, MitTelematicsEditRelatedDriverResponse.class, "telematicsEditRelatedDriver/v1", TELEMATICS);
        appendDefinition(list, MitTelematicsGetRelatedDriversRequest.class, MitTelematicsGetRelatedDriversResponse.class, "telematicsGetRelatedDrivers/v1", TELEMATICS);
        appendDefinition(list, MitTelematicsGetTripDetailsRequest.class, MitTelematicsGetTripDetailsResponse.class, "telematicsGetTripDetails/v1", TELEMATICS);
        appendDefinition(list, MitTelematicsMessagingEnrollmentRequest.class, MitPushNotificationsEnrollmentResponse.class, "telematicsMessagingEnrollment/v1", TELEMATICS);
        appendDefinition(list, MitTelematicsRequestConfirmationCodeRequest.class, MitTelematicsRequestConfirmationCodeResponse.class, "telematicsRequestConfirmationCode/v1", TELEMATICS);
        appendDefinition(list, MitTelematicsRetrieveDriverDataRequest.class, AceTelematicsDriver.class, "telematicsRetrieveDriverData/v1", TELEMATICS);
        appendDefinition(list, MitTelematicsTripCorrectionsRequest.class, MitTelematicsTripCorrectionsResponse.class, "telematicsTripCorrections/v1", TELEMATICS);
        appendDefinition(list, MitTelematicsUpdateEnrollmentRequest.class, MitTelematicsUpdateEnrollmentResponse.class, "telematicsUpdateEnrollment/v1", TELEMATICS);
        appendDefinition(list, MitTelematicsValidateConfirmationCodeRequest.class, MitTelematicsValidateConfirmationCodeResponse.class, "telematicsValidateConfirmationCode/v1", TELEMATICS);
        appendDefinition(list, MitUnenrollFromEBillRequest.class, MitUnenrollFromEBillResponse.class, "unenrollFromEBill/v1", BEAM);
        appendDefinition(list, MitUnenrollFromRecurringPaymentsRequest.class, MitUnenrollFromRecurringPaymentsResponse.class, "unenrollFromRecurringPayments/v1", BEAM);
        appendDefinition(list, MitUpdateAccountEmailRequest.class, MitUpdateAccountEmailResponse.class, "updateAccountEmail/v1", ECAMS);
        appendDefinition(list, MitUpdateAlternatePayerRequest.class, MitUpdateAlternatePayerResponse.class, "updateAlternatePayer/v1");
        appendDefinition(list, MitUpdateNamedInsuredPhoneNumbersRequest.class, MitUpdateNamedInsuredPhoneNumbersResponse.class, "updateNamedInsuredPhoneNumbers/v1", ECAMS);
        appendDefinition(list, MitUpdatePaymentPlanRequest.class, MitUpdatePaymentPlanResponse.class, "updatePaymentPlan/v1");
        appendDefinition(list, MitUpdateSecurityQuestionAnswerRequest.class, MitUpdateSecurityQuestionAnswerResponse.class, "updateSecurityQuestionAnswer/v1", ECAMS);
        appendDefinition(list, MitUpdateTextAlertsRequest.class, MitUpdateTextAlertsResponse.class, "updateTextAlerts/v1");
        appendDefinition(list, MitUpdateUserLoginInformationRequest.class, MitUpdateUserLoginInformationResponse.class, "updateUserLoginInformation/v1", ECAMS);
        appendDefinition(list, MitUpdateUsernameRequest.class, MitUpdateUsernameResponse.class, "updateUsername/v1", ECAMS);
        appendDefinition(list, MitUpdateWalletCardResourceRequest.class, MitUpdateWalletResourceResponse.class, "updateWalletCardResource/v1", BEAM);
        appendDefinition(list, MitUpdateWalletCheckResourceRequest.class, MitUpdateWalletResourceResponse.class, "updateWalletCheckResource/v1", BEAM);
        appendDefinition(list, MitUserLogoutRequest.class, MitUserLogoutResponse.class, "userLogout/v1");
        appendDefinition(list, MitVehicleCareRecallRequest.class, MitVehicleCareRecallResponse.class, "vehicleCareRecall/v1", VEHICLE_CARE);
        appendDefinition(list, MitVehicleSalesQuoteRecallRequest.class, MitVehicleSalesQuoteRecallResponse.class, "vehicleSalesQuoteRecall/v1", SALES);
        appendDefinition(list, MitVerifyRecoveryEmailTokenRequest.class, MitVerifyRecoveryEmailTokenResponse.class, "verifyRecoveryEmailToken/v1", ECAMS);
        appendDefinition(list, MitVerifySecurityAnswersRequest.class, MitVerifySecurityAnswersResponse.class, "verifySecurityAnswers/v1", ECAMS);
        appendDefinition(list, MitVerifySocialSecurityOnFileRequest.class, MitVerifySocialSecurityOnFileResponse.class, "verifySocialSecurityOnFile/v1", ECAMS);
        appendDefinition(list, MitVerifyUserForAccountActivationRequest.class, MitVerifyUserForAccountActivationResponse.class, "verifyUserForAccountActivation/v1", ECAMS);
        appendDefinition(list, MitWebLinkConfigurationRequest.class, MitWebLinkConfigurationResponse.class, "webLinkConfiguration/v1", TIER_ONLY);
    }

    @Override
    protected AceChannel defaultChannel() {
        return AceMitChannels.ISIS;
    }
}