package com.geico.mobile.android.ace.coreframework.webservices.task.livedatatask.model;

import androidx.annotation.StringDef;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Integer representation of network request types.
 *
 * @author Kal Tadesse
 */
@StringDef(value = {
        AceTaskRequestType.ACCOUNT_RECOVERY,
        AceTaskRequestType.ADD_CARD_RESOURCE_TO_WALLET,
        AceTaskRequestType.ADD_CARD_RESOURCE_TO_WALLET_FOR_ALTERNATE_PAYER,
        AceTaskRequestType.ADD_CARD_RESOURCE_TO_WALLET_FOR_NEW_ALTERNATE_PAYER,
        AceTaskRequestType.ADD_CHECK_RESOURCE_TO_WALLET,
        AceTaskRequestType.ADD_CHECK_RESOURCE_TO_WALLET_FOR_ALTERNATE_PAYER,
        AceTaskRequestType.ADD_CHECK_RESOURCE_TO_WALLET_FOR_NEW_ALTERNATE_PAYER,
        AceTaskRequestType.ECAMS_LOG,
        AceTaskRequestType.ENROLL_IN_PUSH,
        AceTaskRequestType.ENROLL_IN_RECURRING_PAYMENT_METHODS_WITH_WALLET,
        AceTaskRequestType.ENROLL_IN_RECURRING_PAYMENTS_BY_ALTERNATE_PAYER_WITH_CARD,
        AceTaskRequestType.ENROLL_IN_RECURRING_PAYMENTS_BY_ALTERNATE_PAYER_WITH_CHECK,
        AceTaskRequestType.ENROLL_IN_RECURRING_PAYMENTS_BY_NEW_ALTERNATE_PAYER_WITH_CARD,
        AceTaskRequestType.ENROLL_IN_RECURRING_PAYMENTS_BY_NEW_ALTERNATE_PAYER_WITH_CHECK,
        AceTaskRequestType.ENROLL_IN_RECURRING_PAYMENT_METHODS_WITH_NEW_CARD,
        AceTaskRequestType.ENROLL_IN_RECURRING_PAYMENT_METHODS_WITH_NEW_CHECK,
        AceTaskRequestType.EVENT_LOG,
        AceTaskRequestType.LEGACY_MAKE_PAYMENT,
        AceTaskRequestType.LOCATION_REQUEST,
        AceTaskRequestType.LEGACY_MAX_PAYMENT_DATE,
        AceTaskRequestType.PAY_LATER_BY_ALTERNATE_PAYER_WITH_CARD,
        AceTaskRequestType.PAY_LATER_BY_ALTERNATE_PAYER_WITH_CHECK,
        AceTaskRequestType.PAY_LATER_BY_CARD,
        AceTaskRequestType.PAY_LATER_BY_CHECK,
        AceTaskRequestType.PAY_LATER_BY_NEW_ALTERNATE_PAYER_WITH_CARD,
        AceTaskRequestType.PAY_LATER_BY_NEW_ALTERNATE_PAYER_WITH_CHECK,
        AceTaskRequestType.PAY_LATER_WITH_STORED_ACCOUNT,
        AceTaskRequestType.PAY_NOW_BY_ALTERNATE_PAYER_WITH_CARD,
        AceTaskRequestType.PAY_NOW_BY_ALTERNATE_PAYER_WITH_CHECK,
        AceTaskRequestType.PAY_NOW_BY_CARD,
        AceTaskRequestType.PAY_NOW_BY_CHECK,
        AceTaskRequestType.PAY_NOW_BY_NEW_ALTERNATE_PAYER_WITH_CARD,
        AceTaskRequestType.PAY_NOW_BY_NEW_ALTERNATE_PAYER_WITH_CHECK,
        AceTaskRequestType.PAY_NOW_WITH_STORED_ACCOUNT,
        AceTaskRequestType.PREPARE_TO_FIND_GAS,
        AceTaskRequestType.PREPARE_TO_UPDATE_TEXT_ALERTS,
        AceTaskRequestType.PREPARE_TO_UPDATE_PAYMENT_PLAN,
        AceTaskRequestType.REGISTER_CLIENT,
        AceTaskRequestType.RETRIEVE_BILLING_INFORMATION,
        AceTaskRequestType.RETRIEVE_CURRENT_DATE_AND_TIME,
        AceTaskRequestType.SPLUNK_LOG,
        AceTaskRequestType.TELEMATICS_EDIT_RELATED_DRIVER,
        AceTaskRequestType.TELEMATICS_GET_RELATED_DRIVERS,
        AceTaskRequestType.TELEMATICS_GET_TRIP_DETAILS,
        AceTaskRequestType.TELEMATICS_MESSAGING_ENROLLMENT,
        AceTaskRequestType.TELEMATICS_REQUEST_CONFIRMATION_CODE,
        AceTaskRequestType.TELEMATICS_RETRIEVE_DRIVER_DATA,
        AceTaskRequestType.TELEMATICS_TRIP_CORRECTIONS,
        AceTaskRequestType.TELEMATICS_UPDATE_ENROLLMENT,
        AceTaskRequestType.TELEMATICS_VALIDATE_CONFIRMATION_CODE,
        AceTaskRequestType.UPDATE_ACCOUNT_EMAIL,
        AceTaskRequestType.UPDATE_TEXT_ALERTS,
        AceTaskRequestType.UNKNOWN,
        AceTaskRequestType.UPDATE_ALTERNATE_PAYER,
        AceTaskRequestType.UPDATE_STORED_CARD_ACCOUNT_IN_WALLET,
        AceTaskRequestType.UPDATE_WALLET_WITH_CARD_RESOURCE,
        AceTaskRequestType.UPDATE_WALLET_WITH_CHECK_RESOURCE,
        AceTaskRequestType.VERIFY_USER,
        AceTaskRequestType.TEST_REQUEST
})
@Target(value = {ElementType.CONSTRUCTOR, ElementType.FIELD, ElementType.METHOD, ElementType.TYPE, ElementType.TYPE_USE})
@Retention(RetentionPolicy.SOURCE)
public @interface AceTaskRequestType {

    String ACCOUNT_RECOVERY = "ACCOUNT_RECOVERY";
    String ADD_CARD_RESOURCE_TO_WALLET = "ADD_CARD_RESOURCE_TO_WALLET";
    String ADD_CARD_RESOURCE_TO_WALLET_FOR_ALTERNATE_PAYER = "ADD_CARD_RESOURCE_TO_WALLET_FOR_ALTERNATE_PAYER";
    String ADD_CARD_RESOURCE_TO_WALLET_FOR_NEW_ALTERNATE_PAYER = "ADD_CARD_RESOURCE_TO_WALLET_FOR_NEW_ALTERNATE_PAYER";
    String ADD_CHECK_RESOURCE_TO_WALLET = "ADD_CHECK_RESOURCE_TO_WALLET";
    String ADD_CHECK_RESOURCE_TO_WALLET_FOR_ALTERNATE_PAYER = "ADD_CHECK_RESOURCE_TO_WALLET_FOR_ALTERNATE_PAYER";
    String ADD_CHECK_RESOURCE_TO_WALLET_FOR_NEW_ALTERNATE_PAYER = "ADD_CHECK_RESOURCE_TO_WALLET_FOR_NEW_ALTERNATE_PAYER";
    String ECAMS_LOG = "ECAMS_LOG";
    String ENROLL_IN_PUSH = "ENROLL_IN_PUSH";
    String ENROLL_IN_RECURRING_PAYMENTS_BY_ALTERNATE_PAYER_WITH_CARD = "ENROLL_IN_RECURRING_PAYMENTS_BY_ALTERNATE_PAYER_WITH_CARD";
    String ENROLL_IN_RECURRING_PAYMENTS_BY_ALTERNATE_PAYER_WITH_CHECK = "ENROLL_IN_RECURRING_PAYMENTS_BY_ALTERNATE_PAYER_WITH_CHECK";
    String ENROLL_IN_RECURRING_PAYMENTS_BY_NEW_ALTERNATE_PAYER_WITH_CARD = "ENROLL_IN_RECURRING_PAYMENTS_BY_NEW_ALTERNATE_PAYER_WITH_CARD";
    String ENROLL_IN_RECURRING_PAYMENTS_BY_NEW_ALTERNATE_PAYER_WITH_CHECK = "ENROLL_IN_RECURRING_PAYMENTS_BY_NEW_ALTERNATE_PAYER_WITH_CHECK";
    String ENROLL_IN_RECURRING_PAYMENT_METHODS_WITH_NEW_CARD = "ENROLL_IN_RECURRING_PAYMENT_METHODS_WITH_NEW_CARD";
    String ENROLL_IN_RECURRING_PAYMENT_METHODS_WITH_NEW_CHECK = "ENROLL_IN_RECURRING_PAYMENT_METHODS_WITH_NEW_CHECK";
    String ENROLL_IN_RECURRING_PAYMENT_METHODS_WITH_WALLET = "ENROLL_IN_RECURRING_PAYMENT_METHODS_WITH_WALLET";
    String EVENT_LOG = "EVENT_LOG";
    String LEGACY_MAKE_PAYMENT = "LEGACY_MAKE_PAYMENT";
    String LEGACY_MAX_PAYMENT_DATE = "LEGACY_MAX_PAYMENT_DATE";
    String LOCATION_REQUEST = "LOCATION_REQUEST";
    String PAY_LATER_BY_ALTERNATE_PAYER_WITH_CARD = "PAY_LATER_BY_ALTERNATE_PAYER_WITH_CARD";
    String PAY_LATER_BY_ALTERNATE_PAYER_WITH_CHECK = "PAY_LATER_BY_ALTERNATE_PAYER_WITH_CHECK";
    String PAY_LATER_BY_CARD = "PAY_LATER_BY_CARD";
    String PAY_LATER_BY_CHECK = "PAY_LATER_BY_CHECK";
    String PAY_LATER_BY_NEW_ALTERNATE_PAYER_WITH_CARD = "PAY_LATER_BY_NEW_ALTERNATE_PAYER_WITH_CARD";
    String PAY_LATER_BY_NEW_ALTERNATE_PAYER_WITH_CHECK = "PAY_LATER_BY_NEW_ALTERNATE_PAYER_WITH_CHECK";
    String PAY_LATER_WITH_STORED_ACCOUNT = "PAY_LATER_WITH_STORED_ACCOUNT";
    String PAY_NOW_BY_ALTERNATE_PAYER_WITH_CARD = "PAY_NOW_BY_ALTERNATE_PAYER_WITH_CARD";
    String PAY_NOW_BY_ALTERNATE_PAYER_WITH_CHECK = "PAY_NOW_BY_ALTERNATE_PAYER_WITH_CHECK";
    String PAY_NOW_BY_CARD = "PAY_NOW_BY_CARD";
    String PAY_NOW_BY_CHECK = "PAY_NOW_BY_CHECK";
    String PAY_NOW_BY_NEW_ALTERNATE_PAYER_WITH_CARD = "PAY_NOW_BY_NEW_ALTERNATE_PAYER_WITH_CARD";
    String PAY_NOW_BY_NEW_ALTERNATE_PAYER_WITH_CHECK = "PAY_NOW_BY_NEW_ALTERNATE_PAYER_WITH_CHECK";
    String PAY_NOW_WITH_STORED_ACCOUNT = "PAY_NOW_WITH_STORED_ACCOUNT";
    String PREPARE_TO_FIND_GAS = "PREPARE_TO_FIND_GAS";
    String PREPARE_TO_UPDATE_PAYMENT_PLAN = "PREPARE_TO_UPDATE_PAYMENT_PLAN";
    String PREPARE_TO_UPDATE_TEXT_ALERTS = "PREPARE_TO_UPDATE_TEXT_ALERTS";
    String REGISTER_CLIENT = "REGISTER_CLIENT";
    String RETRIEVE_BILLING_INFORMATION = "RETRIEVE_BILLING_INFORMATION";
    String RETRIEVE_CURRENT_DATE_AND_TIME = "RETRIEVE_CURRENT_DATE_AND_TIME";
    String SPLUNK_LOG = "SPLUNK_LOG";
    String TELEMATICS_EDIT_RELATED_DRIVER = "TELEMATICS_EDIT_RELATED_DRIVER";
    String TELEMATICS_GET_RELATED_DRIVERS = "TELEMATICS_GET_RELATED_DRIVERS";
    String TELEMATICS_GET_TRIP_DETAILS = "TELEMATICS_GET_TRIP_DETAILS";
    String TELEMATICS_MESSAGING_ENROLLMENT = "TELEMATICS_MESSAGING_ENROLLMENT";
    String TELEMATICS_REQUEST_CONFIRMATION_CODE = "TELEMATICS_REQUEST_CONFIRMATION_CODE";
    String TELEMATICS_RETRIEVE_DRIVER_DATA = "TELEMATICS_RETRIEVE_DRIVER_DATA";
    String TELEMATICS_TRIP_CORRECTIONS = "TELEMATICS_TRIP_CORRECTIONS";
    String TELEMATICS_UPDATE_ENROLLMENT = "TELEMATICS_UPDATE_ENROLLMENT";
    String TELEMATICS_VALIDATE_CONFIRMATION_CODE = "TELEMATICS_VALIDATE_CONFIRMATION_CODE";
    String TEST_REQUEST = "TEST_REQUEST";
    String UNKNOWN = "UNKNOWN";
    String UPDATE_ACCOUNT_EMAIL = "UPDATE_ACCOUNT_EMAIL";
    String UPDATE_ALTERNATE_PAYER = "UPDATE_ALTERNATE_PAYER";
    String UPDATE_STORED_CARD_ACCOUNT_IN_WALLET = "UPDATE_STORED_CARD_ACCOUNT_IN_WALLET";
    String UPDATE_TEXT_ALERTS = "UPDATE_TEXT_ALERTS";
    String UPDATE_WALLET_WITH_CARD_RESOURCE = "UPDATE_WALLET_WITH_CARD_RESOURCE";
    String UPDATE_WALLET_WITH_CHECK_RESOURCE = "UPDATE_WALLET_WITH_CHECK_RESOURCE";
    String VERIFY_USER = "VERIFY_USER";
}
